### ISSUE TITLE
Where to get LSUN dataset

### ISSUE THREAD

**Issue by tengyuliu** [martinarjovsky/WassersteinGAN#10]
Hi, I'm new to computer vision and is trying to get up to speed with everything. When I run the 

`python main.py --dataset lsun --dataroot [dataroot] --cuda`

command there is an error saying `lmdb.Error: [dataroot]/bedroom_train_lmdb: no such file or directory`. It looks like that I need to download the dataset myself. Can you provide a pointer to which I can get the dataset? Thank you very much!

**Comment by soumith** [comment]
http://lsun.cs.princeton.edu/2016/
