### ISSUE TITLE
Fixed noise and conditions for Wasserstein GAN training

### ISSUE THREAD

**Issue by rafaelvalle** [martinarjovsky/WassersteinGAN#12]
Would you suggest having fixed noise and conditions when looking at outputs of the generator to evaluate progress?

**Comment by martinarjovsky** [comment]
Hi!
For sample looking: Yes! :). If you don't have it fixed it's very easy to fool yourself and cherry-pick the samples when looking at wether the algorithm is doing better / worse than before. This helps keep that bias in check.

For learning curves: if you change the batch at every time it's a training curve, if you keep it fixed (and held-out) it's akin to a validation curve, depends on which one you want!
