### ISSUE TITLE
inputv update

### ISSUE THREAD

**Issue by elPistolero** [martinarjovsky/WassersteinGAN#15]
Shouldn't there be an update on inputv with the real data after line [182](https://github.com/martinarjovsky/WassersteinGAN/blob/master/main.py#L182), where the real_data is copied into inputv:
```python
inputv.data.resize_(real_cpu.size()).copy_(real_cpu)
```

Then line [191](https://github.com/martinarjovsky/WassersteinGAN/blob/master/main.py#L191) also has to be updated.

Is this a bug or am I missing something about how pytorch works?

**Comment by soumith** [comment]
within one small commit I introduced like 100 bugs. Sorry about that. this is fixed in master via https://github.com/martinarjovsky/WassersteinGAN/commit/7eee65dc9cd08414dfcd5718b5cbe7b4c0360495
