### ISSUE TITLE
is the estimate of Wasserstein distance negative?

### ISSUE THREAD

**Issue by aosokin** [martinarjovsky/WassersteinGAN#17]
In continuation with the discussion in issue #9, I'm still missing something about the critic objective.
Isn't `Loss_D` supposed to be the approximation of the Wasserstein distance? Then, if the critic is trained to optimalilty, the distance should be at least positive.
Related to this, the actual objective of the critic is going up when training. Does this mean that the estimate of the Wasserstein distance is not improving? Should the picture be the same if we train the critic to optimality at each iteration?

**Comment by martinarjovsky** [comment]
- Loss_D is the Wasserstein estimate. You need to plot - Loss_D

**Comment by martinarjovsky** [comment]
Dang, github converted my minus sign into an item list. - Loss_D is the Wasserstein estimate and what you should plot. Considering what you said that curve will be positive and going down as expected.

**Comment by aosokin** [comment]
Thanks, finally understood what actually happens.
