### ISSUE TITLE
resize problem

### ISSUE THREAD

**Issue by yichuan9527** [martinarjovsky/WassersteinGAN#20]
Hello! I run your WGAN's code.
I get this bug
 input.resize_as_(real_cpu).copy_(real_cpu)
TypeError: resize_as_ received an invalid combination of arguments - got (!torch.FloatTensor!), but expected (torch.cuda.FloatTensor template)
How to solve it?

**Comment by vintermann** [comment]
This looks a lot like the issue which was just addressed by https://github.com/martinarjovsky/WassersteinGAN/pull/19 .

**Comment by soumith** [comment]
fixed via https://github.com/martinarjovsky/WassersteinGAN/pull/19

**Comment by yichuan9527** [comment]
I solve this problem!
Thank very much!
It bother me a lot of time!
Thanks again
