### ISSUE TITLE
Questions about the D_loss

### ISSUE THREAD

**Issue by yichuan9527** [martinarjovsky/WassersteinGAN#21]
Hello, your method computing the d_loos is that using 
`errD_real.backward(one)` 
`errD_fake.backward(mone).`
But why not using 
`errD = errD_real - errD_fake`
`errD.backward()`

It is faster than the previous  attenuation to 0

**Comment by edgarriba** [comment]
@soumith any reason for that?

**Comment by soumith** [comment]
yea that's fine to do.
