### ISSUE TITLE
Why is data always normalized w/ hardcoded mean/std = 0.5

### ISSUE THREAD

**Issue by mjdietzx** [martinarjovsky/WassersteinGAN#26]
Can someone explain why this is done: https://github.com/martinarjovsky/WassersteinGAN/blob/master/main.py#L70

**Comment by soumith** [comment]
mostly because we are extremely lazy to find the datasets true mean/stdv.

images are loaded in at range [0, 1] and we just wanted to renormalize to [-1, 1]
