### ISSUE TITLE
convert the real images and generated images back to original format to display???

### ISSUE THREAD

**Issue by eriche2016** [martinarjovsky/WassersteinGAN#33]
Hi, [here](https://github.com/martinarjovsky/WassersteinGAN/blob/master/main.py#L221-L224) when displaying the images , donot we need to  convert back to the original images value range before storing them to disk.

**Comment by LukasMosser** [comment]
@eriche2016 I believe that happens in vutils.save_image

https://github.com/pytorch/vision/blob/master/torchvision/utils.py#L81

**Comment by eriche2016** [comment]
@LukasMosser , hi, i notice that [here](https://github.com/martinarjovsky/WassersteinGAN/blob/master/main.py#L70) the real image tensor  ```Input```  has been normalized to ```Out``` by mean = [0.5, 0.5, 0.5] and 
std = [0.5, 0.5, 0.5], should not the transformed value be converted back by using ```Out * 0.5 + 0.5``` before storing back to the disk.

**Comment by eriche2016** [comment]
Hi, i think we should converted back by inserting the line
```
real_cpu = real_cpu.mul(0.5).add(0.5) 

```
above [here](https://github.com/martinarjovsky/WassersteinGAN/blob/master/main.py#L221)
and 
```
fake.data = fake.data.mul(0.5).add(0.5)
```
above [here](https://github.com/martinarjovsky/WassersteinGAN/blob/master/main.py#L223),  otherwise, the generated images will be not good looking with some sharp weird edges.
