### ISSUE TITLE
Question about 'one' and 'mone'

### ISSUE THREAD

**Issue by sz128** [martinarjovsky/WassersteinGAN#41]
I just got confusion about the "one" and "mone" used in "backward()". The goal of discriminator "D" is to maximize the output of netD for real data, but minimize the output of netD for fake data (as I understand it). While "backward" and "optimizerD" are minimizing a loss function.  Therefore, I think "errD_real.backward(one)" should be "errD_real.backward(mone)", and "errD_fake.backward(mone)" should be "errD_fake.backward(one)". That is my opinion. Could you give some explanations? Thank you!

**Comment by darid** [comment]
发自我的 iPhone

**Comment by XavierLinNow** [comment]
hi, @sz128 . I have the same questions. Have you figured it out?

**Comment by martinarjovsky** [comment]
See https://github.com/martinarjovsky/WassersteinGAN/issues/9

**Comment by XavierLinNow** [comment]
@martinarjovsky , thanks!
