### ISSUE TITLE
Why there is no netG.parameters.requires_grad = False when updating netD?

### ISSUE THREAD

**Issue by fungtion** [martinarjovsky/WassersteinGAN#42]
I'm new to the GAN, what I understand about it is that netG and netD should be optimized alternatively，but I cannot find `netG.parameters.requires_grad = False` when updating netD, I get confused about it.

**Comment by kunrenzhilu** [comment]
You freeze the netG when train netD

**Comment by fungtion** [comment]
@kunrenzhilu you mean updating netG and netD when train netD?

**Comment by fungtion** [comment]
@kunrenzhilu I see, setting Variable `volatile=True` means 'netG.parameters.requires_grad = False'

**Comment by fungtion** [comment]
@kunrenzhilu I see, setting Variable `volatile=True` means 'netG.parameters.requires_grad = False'
