### ISSUE TITLE
Where can I find bibtex of Wasserstein GAN and related works?

### ISSUE THREAD

**Issue by ghost** [martinarjovsky/WassersteinGAN#59]

**Comment by martinarjovsky** [comment]
You can use this one (which you can find in https://leon.bottou.org/papers)

@inproceedings{arjovsky-chintala-bottou-2017,
  author = {Arjovsky, Martin and Chintala, Soumith and Bottou, L\'{e}on},
  title = {Wasserstein Generative Adversarial Networks},
  year = {2017},
  booktitle = {Proceedings of the 34nd International Conference on Machine Learning, {ICML} 2017, Sydney, Australia, 7-9 August, 2017},
  url = {http://leon.bottou.org/papers/arjovsky-chintala-bottou-2017},
}

Cheers!
Martin
