### ISSUE TITLE
Results on cifar10 very bad even if trained for over 1000 epochs

### ISSUE THREAD

**Issue by FANG-Xiaolin** [martinarjovsky/WassersteinGAN#64]
Dear authors,

I used the default parameters and trained it on Cifar10 datasets for over 1000 epochs, but the results are not very good looking. It is blurry and can hardly recognize the category. Did you use another set of parameters for cifar10?

Looking forward to your reply. Thanks.

**Comment by martinarjovsky** [comment]
We have no CIFAR10 results in the paper so I'm not sure what you're referring to. You may want to take a look at https://github.com/igul222/improved_wgan_training where we provide a very good CIFAR10 model.

Cheers :)
Martin
