### ISSUE TITLE
Results cannot be reproduced.

### ISSUE THREAD

**Issue by zeakey** [martinarjovsky/WassersteinGAN#67]
Same as mentioned in #62 and #64, the results on CIFAR10 dataset cannot be reproduced!

I trained with the default settings for 100 epochs (which I think is enough), but the results
still don't make sense.

Here is the example fake images generated via the Generator:
![screenshot from 2018-12-01 15-16-04](https://user-images.githubusercontent.com/6763078/49325412-efa33300-f57c-11e8-8629-4fbb45459470.png)

Any body reproduced the results on CIFAR10 (or LSUN bedroom) dataset, can you please tell the training details?

**Comment by FANG-Xiaolin** [comment]
Hi Zeakey,

Do you have any solution to this problem? Is there any necessary changes that should be made, e.g. to the parameters? Thanks

**Comment by martinarjovsky** [comment]
I don't know what 'results cannot be reproduced'. We don't have any CIFAR-10 results in the paper. Maybe you want to take a look at https://github.com/igul222/improved_wgan_training and https://arxiv.org/abs/1704.00028 .

Cheers :)
Martin
